### PR TITLE
Allow more colors and external control for render

### PR DESCRIPTION
**Pull request by funnisimo**
Changed the style array to 32 bits - 16 each for bg and fg.
Allow Scene to either auto render (default) or to be handled externally (via constructor option)
Made demo more dynamic.

### CODE REVIEW

**Comment by ondras** [comment]
Hi @funnisimo ,

thanks for your contribution! However, I would like to see some discussion prior to implementation. Let's split it by individual changes:

1) README, amiga palette and demo - thanks for these, I have no issues here. Even though the "demo" is more of a debug page, not linked anywhere, probably going to get deleted soon.

2) palette size: is it reasonable to expect more than 256 colors in a tile-based game? And even if people *do* need that many colors, ideally we should only upload 16-bit values for palettes with <= 256 colors. This would mean switching the underlying buffer based on the palette size.

    I am not a big fan of having to specify the palette size in advance (constructor argument). People might configure the palette at runtime, growing it as necessary.

    Finally, I am fairly certain that both canvas and texture sizes are limited. We cannot have a canvas width=65536. (But we can make the palette canvas a square of 256x256 pixels.)

3) external render - I am puzzled by this one. What problem is this adjustment trying to solve? The rendering loop is intentionally implemented by fastiles so that the user does not need to interfere. If you absolutely want to call the rendering routine itself, I would suggest:

    a) making the relevant methods `protected` instead of `private`
    b) subclassing the Scene and re-implementing the behavior as necessary


Perhaps you can split this PR into individual features so we can discuss them in threads?

**Comment by ondras** [comment]
>     2\. This would mean switching the underlying buffer based on the palette size.

Damn, the style info is also hardcoded in the fragment shader, so we cannot switch these easily!

**Comment by funnisimo** [comment]
Cool.  No worries.  

Sorry about mixing too many ideas into 1 PR.  I am not good at holding back my enthusiasm sometimes.  

1 - I like the dynamic demo just so it shows off how cool it is.
1 - The amiga palette is only useful if we keep the 4096 color capability.

2 - I wanted to add the extra colors for my roguelike.  I am probably fooling myself that I get benefit from it, but at this point that is where I am.  The goal that I have is something that is visually close to Brogue.  If you look at the way water, gas, explosions, and the title screen are done, you will see a lot of subtle shading of colors.  I feel like 256 colors just would not cut it for this, but 4096 seems like enough.  

2 - Good point on the growing as necessary.  I did not think about that usage pattern, although I don’t immediately think of a reason to build a game this way.  If this is a real feature you want to maintain then I’d have to think about the implementation some more.  [If we increase the size of the canvas, do the prior paints stay or do they get messed up?]

2 - The default for the palette size should be 256 colors if you supply no parameters.  I can also see setting that as the minimum size so that the grow the palette pattern from above continues to work just fine up to 256.  We could then continue to grow it in chunks (256?) if someone wants to keep adding all the way to 65536.

2- Good point on the line vs square.  I will take a stab at that.  That also fits well with the grow it by 256 idea.

3 - The self controlled render is just for people who want it.  By default it renders by itself.  I wanted that because I do other stuff in my RAF call and I would like to have certainty of the ordering of those operations with the rendering - like updating some of my animations.  If I can just call render when I am ready things are more deterministic for me.

3 - By making render public we limit the work that someone using this pattern has to go through to do it.  Low cost to user instead of figuring out a subclass.  However it comes at the cost of that boolean field.  Making them protected is fine in the end though for me since I figured out how to do that I wanted already.  

I am not sure how to split the PR.  Why don’t you close/reject it.  

I will remove the stuff for #3 and then update the palette code to use the 256xN logic so that it grows automagically for users (no need for size hint).  Then I will resubmit a PR for that change. 

After we get that in a good place, I will come back to #3.

Sound good?

**Comment by ondras** [comment]
> 1 - The amiga palette is only useful if we keep the 4096 color capability.

I see. I am not opposed to >256 *per se*, but I think that majority of users would want to stick with <256 (and thus less bytes to transfer from RAM to GPU).

> 2 - The default for the palette size should be 256 colors if you supply no parameters. I can also see setting that as the minimum size so that the grow the palette pattern from above continues to work just fine up to 256. We could then continue to grow it in chunks (256?) if someone wants to keep adding all the way to 65536.
> 
> 2- Good point on the line vs square. I will take a stab at that. That also fits well with the grow it by 256 idea.

Yes, growing the square by adding 256px lines sounds like the best approach to me so far. You will need to copy the canvas on every grow, though, because resizing the `<canvas>` node erases its contents. I do not see that as a problem.

I am still not sure how to dynamically switch the SHORT to INT without having to provide two fragment shaders. If you are aware of a solution, throw it at me!



>  I wanted that because I do other stuff in my RAF call and I would like to have certainty of the ordering of those operations with the rendering - like updating some of my animations. If I can just call render when I am ready things are more deterministic for me.

This is an interesting point! I understand your argument about having a control of RAF-related stuff. On the other hand, do you really need/want your app-level animation loop? The stuff that happens in your game is not related to the rendering itself; if you have a flying projectile, you update its position based on a physics loop that does not need to be related/synced to the rendering. Games often use their own `setInterval` loop to update *state*, while maintaining an unrelated rendering loop (with a different frequency).

(This is mostly me thinking out loud because I am going to solve very similar issues once I start building real stuff atop fastiles. So we shall see...)



> 3 - By making render public we limit the work that someone using this pattern has to go through to do it. Low cost to user instead of figuring out a subclass. However it comes at the cost of that boolean field. Making them protected is fine in the end though for me since I figured out how to do that I wanted already.

My ultimate goal here is to keep the API surface *as small as possible*, by not introducing additional properties, methods and arguments where not necessary. Please try sticking with the subclassing (and `protected`) approach; if it turns out to be too limiting, we can always make some more parts movable and/or public.



> I am not sure how to split the PR. Why don’t you close/reject it.

Yep.



> I will remove the stuff for #3 and then update the palette code to use the 256xN logic so that it grows automagically for users (no need for size hint). Then I will resubmit a PR for that change.
> 
> After we get that in a good place, I will come back to #3.
> 
> Sound good?

Great, agreed!

**Pull request closed without merging**
